### ISSUE TITLE
Working on Unity but not on Device

### ISSUE THREAD

**Issue by nataliapoppe9** [elringus/unity-google-drive#132]
Images are being uploaded to Drive when I run on Unity, but when I build the App and run it on my Android device the app closes down and doesnt open up Google Drive Login.

**Comment by elringus** [comment]
Probably due to some exception. Debug to figure what's wrong.

**Comment by nataliapoppe9** [comment]
Can you explain a little more?
Can I debug from my android device?
Everything is working fine on simulator, no errors or warnings. How/Where can I check if there is exceptions ?

**Comment by nataliapoppe9** [comment]
public Texture2D image;
 void Update()
    {
        if ((Input.touchCount > 0) && (Input.GetTouch(0).phase == TouchPhase.Ended))
        {
            StartCoroutine("FileCreate");
        }
    }

   public IEnumerator FileCreate()
    {
        var content = image.EncodeToPNG();
        var file = new UnityGoogleDrive.Data.File() { Name = "Test Upload", Content = content };
        var request = GoogleDriveFiles.Create(file);
        yield return request.Send();
        print(request.IsError);
        print(request.ResponseData.Content);
        print(request.ResponseData.Id);
    }

**Comment by elringus** [comment]
Consult Unity docs for debugging on devices.

**Comment by nataliapoppe9** [comment]
I debugged from my Device

Can you help with this information? 
![Captura de pantalla 2023-12-20 180353](https://github.com/elringus/UnityGoogleDrive/assets/104201410/06cd93d3-ff90-4ac4-9c48-561db61a4e1c)

I don't really undrestand whats happening there..

**Comment by nataliapoppe9** [comment]
The thing is that on the simulator it allows me to sign in to google, but on my phone it just closes Down

**Comment by nataliapoppe9** [comment]
Does this have something to do with https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationException.java ?

**Comment by nataliapoppe9** [comment]
Can you help pleasee?

**Comment by shradhz06** [comment]
Same issue I am facing there is no way It is working on android devices.

**Comment by shradhz06** [comment]
> I debugged from my Device
> 
> Can you help with this information? ![Captura de pantalla 2023-12-20 180353](https://private-user-images.githubusercontent.com/104201410/291964571-06cd93d3-ff90-4ac4-9c48-561db61a4e1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NDA0OTksIm5iZiI6MTczMTg0MDE5OSwicGF0aCI6Ii8xMDQyMDE0MTAvMjkxOTY0NTcxLTA2Y2Q5M2QzLWZmOTAtNGFjNC05YzQ4LTU2MWRiNjFhNGUxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMDQzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWY1YzBhZDU5MWQ4NDZhMTA2NjczN2RjMDJkNmU3OTgxZmI0ZTQ2MjQ4NjUzNTVmZjA3NjNhZDRlNjYyMGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.H1BrK5RPM8MkoSqPgkr1q-R01UMH4LUsIGMebWkp8mo)
> 
> I don't really undrestand whats happening there.. But fatal error sounds bad

@nataliapoppe9 were you able to fix it ?
