### ISSUE TITLE
Add an option to use specific port for redirct uri under loopback scheme

### ISSUE THREAD

**Issue by nicolasboattini** [elringus/unity-google-drive#135]
Every time I run my application, I notice that the Redirect URI used with the UnityGoogleDrive library in the Google Cloud Console automatically changes, appending a string of random port numbers.

I have developed a photobooth app, and when it's time to upload the photo to Google Drive, it always prompts for permissions. I couldn't figure out the issue until I noticed that the redirection link was different every time, for example:

http://localhost:10158/?state=[...]
http://localhost:10621/?state=[...]
http://localhost:10657/?state=[...]
I've attempted to address the problem by changing the loopback URI in the configuration file of the library. I also updated my OAuth Client ID multiple times, adjusting the authorized redirect URIs to match the current port.

I would expect the Redirect URI to remain constant after each execution, so I don't have to grant access every time I want to upload a photo, especially since all the photos are uploaded by the same account and into the same folder.

Is there a way to have a static redirect URI for every iteration of the application?

Operating System: Windows
Unity Editor Version: 2022.3.12f1

Edit:
Of course i was using  "http://localhost" as my loopback uri and the redirect one too, so that way it worked but prompting for permissions.
Then i tried adding a port, for example "http://localhost:8888" to both fields and started getting this error:

ArgumentException: Invalid port.
System.Net.ListenerPrefix.CheckUri (System.String uri) (at <36d5d97f0e39429283d80156f1c7f1fc>:0)
System.Net.HttpListenerPrefixCollection.Add (System.String uriPrefix) (at <36d5d97f0e39429283d80156f1c7f1fc>:0)
UnityGoogleDrive.LoopbackAccessTokenProvider.ExecuteFullAuth () (at ./Library/PackageCache/com.elringus.unitygoogledrive@3aa1d8fc7a/Runtime/Authorization/LoopbackAccessTokenProvider.cs:111)
UnityGoogleDrive.LoopbackAccessTokenProvider.ProvideAccessToken () (at ./Library/PackageCache/com.elringus.unitygoogledrive@3aa1d8fc7a/Runtime/Authorization/LoopbackAccessTokenProvider.cs:51)
UnityGoogleDrive.AuthController.RefreshAccessToken () (at ./Library/PackageCache/com.elringus.unitygoogledrive@3aa1d8fc7a/Runtime/Authorization/AuthController.cs:45)
UnityGoogleDrive.GoogleDriveRequest`1[TResponse].HandleUnauthorizedResponse () (at ./Library/PackageCache/com.elringus.unitygoogledrive@3aa1d8fc7a/Runtime/GoogleDriveRequest.cs:258)
UnityGoogleDrive.GoogleDriveRequest`1[TResponse].HandleWebRequestDone (UnityEngine.AsyncOperation requestYield) (at ./Library/PackageCache/com.elringus.unitygoogledrive@3aa1d8fc7a/Runtime/GoogleDriveRequest.cs:235)
UnityEngine.AsyncOperation.InvokeCompletionEvent () (at <30adf90198bc4c4b83910c6fb1877998>:0)

And it was when I changed the URI to "http://localhost:8687/" adding a "/" at the end that I found in the OAuth dialog that I had Error 400: redirect_uri_mismatch, and the request details show this: redirect_uri="http://localhost:8888/:11402".

**Comment by nicolasboattini** [comment]
Searching a bit further i found this: https://github.com/elringus/unity-google-drive/blob/master/Assets/UnityGoogleDrive/Runtime/Authorization/LoopbackAccessTokenProvider.cs

where there is a method called ExecuteFullAuth() that implements this: 
 // Creates a redirect URI using an available port on the loopback address.
            redirectUri = $"{settings.LoopbackUri}:{GetRandomUnusedPort()}";
            
I assume that here is where my problem resides cause its clearly using a random port. It really has to be like that? Isn't there a way to have a static port?

**Comment by elringus** [comment]
It has to be unused, but not necessarily random. The thing is, we do not know which port is unused on user machine. I guess there could be an option in config to use specific port instead of finding a random unused one.

**Comment by nicolasboattini** [comment]
Thanks for quick reply. I guess that having a field to use specific port set by the user could be a gamechanger enhancement nowadays. I'd like to do it myself but i'm afraid my knowledgements aren't that high, but i'll give it a try, if i find something i'll make a PR.

**Comment by nicolasboattini** [comment]
Done! Wasn't that hard i think.
Requesting for aproval here: https://github.com/elringus/unity-google-drive/pull/136

**Comment by nicolasboattini** [comment]
Nvm, it have a static port but the prompting for permissions stills appearing for every photo I try to upload. I don't know what else to do. Maybe it is some missing configuration in mi application in Google Cloud or maybe there is a way to set a default sign-in in the config and use that.

**Comment by elringus** [comment]
@nicolasboattini This is probably due to auth token not being cached or used. Try building the sample project and check if it reproduces for you to figure if that's related with your custom app or with the plugin. Feel free to open another issue to discuss this.
